global:
  enabled: true
server:
  ha:
    enabled: true
    replicas: 3
  dataStorage:
    enabled: true
  extraVolumes:
    - name: gcs-credentials
      secret:
        secretName: vault-gcs-credentials
  extraVolumeMounts:
    - name: gcs-credentials
      mountPath: /etc/vault/credentials
      readOnly: true
  config: |
    storage "gcs" {
      bucket = "vault-storage-bucket"
      credentials_file = "/etc/vault/credentials/gcs.json"
    }
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
    ui = true